### ISSUE TITLE
BlockLogger.txt needs formatting for better understanding

### ISSUE THREAD

**Issue by kauf0** [Blayung/my-plugin#4]
Just suggesting, as soon as @Blayung opened #3 and is targeting to improve log file.

Log file isn't really readable at the current state for there are fields where 6 numbers in a row which casual user couldn't read. I mean, It'd be cool if logs entries were just like in game or smth. So I'd like to offer my guesses on this.

For example we take this event:
`0 1707008410 #LEAVES_DECAY world 25 77 117 18 8 -1`
would look like `[whatever these nums are] at world x: 25 y: 77 z: 117, #LEAVES_DECAY 18:8(OAK_LEAVES)`

Or take the steal event:
`2 1707008773 kauf0 world 69 64 129 299 0 1`
It seems that "STOLE" and "PUT" haven't been added to the list yet since they were just implemented yesterday, so that's ok. Would look like this: `at world x: _ y: _ z: _, kauf0 STOLE 299:0 LEATHER_ARMOUR, amount: 1` or smth.

**Comment by Blayung** [comment]
I've added item support 2 weeks ago, but it requires [some changes in canyon's code](https://github.com/canyonmodded/canyon/pull/67) that haven't been pulled yet so item support still isn't on the main branch.

This suggestion is not something I will implement, it's quite a waste of time for me because on a normal server there will be loads and loads of these entries and there'll be no reason to read them from this file. You are supposed to use `/blocklog` for this, and #3 is also made to improve the command, leaving `block-log-book.txt` as a file meant to be read by the plugin, not by humans. It's unnecessary complexity.
